title: The Fastest Mouse Clicker for Windows
logo: /favicon_large.png
description: The fastest hardware-limited mouse clicker for Windows with command line support.
show_downloads: true
theme: jekyll-theme-minimal